/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiKeyManager: typeof import('./src/components/ApiKeyManager.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    ModelConfigItem: typeof import('./src/components/ModelConfigItem.vue')['default']
    ModelGroupCard: typeof import('./src/components/ModelGroupCard.vue')['default']
    ModelGroupEditor: typeof import('./src/components/ModelGroupEditor.vue')['default']
    ModelResponsesDisplay: typeof import('./src/components/ModelResponsesDisplay.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
